//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RammTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public System.Guid Id { get; set; }
        public string Description { get; set; }
        public bool Done { get; set; }
        public System.Guid PersonId { get; set; }
    }
}
